name: GitHub Actions

on: push

jobs:
  build-on-alpine-linux:
    name: Build on Alpine Linux
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v3
      - run: apk add libjpeg-turbo-dev libjpeg-turbo-static
      - run: shards build --no-debug --production --release --static
      - uses: actions/upload-artifact@v3
        with:
          name: thumbnailer
          path: bin/thumbnailer
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bin/thumbnailer
  check:
    name: Check
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v3
      - run: shards install
      - run: bin/ameba
      - run: crystal tool format --check
